name: Markdown-index-CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch 
      pull-requests: write  # To create a PR from that branch
    steps:
      # Check
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: |
          echo '如果存在则删除 ./index.html：'
          if [ ! -f "./index.html" ];then
          echo "文件不存在"
          else
          rm -d ./index.html
          fi

      # Deploy
      - uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: . # The folder the action should deploy.
